# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: zxk000000000
        password: 7baebfdf-4973-47a3-90aa-7bc45a81eeeb
    - name: Git Clone Action
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: https://github.com/xinkunZ/PornHub-downloader-python.git
        ref: master
    - name: Build with Maven
      run: mvn -B -Ddocker_tag=latest deploy -Pdocker --file pom.xml
